[workspace]

members = [
    "backend",
    "core",
    "frontend",
    "test_generation"
]

[profile.release.package.segemehl_21_backend]
debug = true

[profile.release.package.segemehl_21_frontend]
opt-level = "s"