cargo run --release --bin segemehl_21_backend -- --input ./test_data/unmapped/bam/output_unmapped_0.bam --output ./test_data/unmapped/stat/output_unmapped_0.stat
cargo run --release --bin segemehl_21_backend -- --input ./test_data/unmapped/bam/output_unmapped_1.bam --output ./test_data/unmapped/stat/output_unmapped_1.stat
cargo run --release --bin segemehl_21_backend -- --input ./test_data/unmapped/bam/output_unmapped_2.bam --output ./test_data/unmapped/stat/output_unmapped_2.stat
cargo run --release --bin segemehl_21_backend -- --input ./test_data/unmapped/bam/output_unmapped_3.bam --output ./test_data/unmapped/stat/output_unmapped_3.stat
cargo run --release --bin segemehl_21_backend -- --input ./test_data/unmapped/bam/output_unmapped_4.bam --output ./test_data/unmapped/stat/output_unmapped_4.stat
cargo run --release --bin segemehl_21_backend -- --input ./test_data/unmapped/bam/output_unmapped_5.bam --output ./test_data/unmapped/stat/output_unmapped_5.stat
cargo run --release --bin segemehl_21_backend -- --input ./test_data/unmapped/bam/output_unmapped_6.bam --output ./test_data/unmapped/stat/output_unmapped_6.stat
cargo run --release --bin segemehl_21_backend -- --input ./test_data/unmapped/bam/output_unmapped_7.bam --output ./test_data/unmapped/stat/output_unmapped_7.stat
cargo run --release --bin segemehl_21_backend -- --input ./test_data/unmapped/bam/output_unmapped_8.bam --output ./test_data/unmapped/stat/output_unmapped_8.stat
cargo run --release --bin segemehl_21_backend -- --input ./test_data/unmapped/bam/output_unmapped_9.bam --output ./test_data/unmapped/stat/output_unmapped_9.stat